#!/bin/bash
git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac
git clone https://github.com/Odyssey2247/nvimDE tmpVim
mv tmpVim/* ~/.config/nvim/
rm -rf tmpVim

echo "Now open nvim and run"
echo "	:PackUpdate"
