#!/bin/bash
git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac
git clone https://github.com/joselbr2099/NeoIDE tmpVim
mv tmpVim/* ~/.config/nvim/
rm -rf tmpVim
echo -e "-------------------------------------------------"
echo "Now open nvim (ignore errors) and install pluginns"
echo -e "-------------------------------------------------"
nvim +PackUpdate
