#!/bin/bash
git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac
git clone https://github.com/joselbr2099/NeoIDE tmpVim
mv tmpVim/* ~/.config/nvim/
rm -rf tmpVim
echo -e "-------------------------------------------------"
echo "nvim install plugins (ignore errors)..."
echo -e "-------------------------------------------------"
#nvim +PackUpdate +qa -u ~/.config/nvim/tmp.vim --headless

nvim +PackUpdate +qa --headless

echo -e "-------------------------------------------------"
echo "installation finish now open nvim"
echo -e "-------------------------------------------------"
